/** Spaces per indentation level generated by the plugin. */
export const TASK_INDENT = 4;

/** How deep a line's leading spaces and tabs reach, a tab counting as one level. */
export function indentWidth(line: string): number {
  return [...(/^[ \t]*/.exec(line)?.[0] ?? "")].reduce((width, char) => width + (char === "\t" ? TASK_INDENT : 1), 0);
}
